enum SlotSymbol {
  zu,
  nn,
  da,
  bar,
  watermelon,
  bell,
  plum,
  cherry,
  replay;

  static List<SlotSymbol> get first => [
        bell,
        watermelon,
        plum,
        replay,
        bell,
        zu,
        watermelon,
        plum,
        cherry,
        replay,
        bar,
        plum,
        watermelon,
        replay,
        bell,
        da,
        plum,
        watermelon,
        nn,
        replay,
        plum,
      ];

  static List<SlotSymbol> get second => [
        replay,
        plum,
        bell,
        replay,
        watermelon,
        nn,
        plum,
        bell,
        replay,
        watermelon,
        da,
        plum,
        replay,
        cherry,
        plum,
        watermelon,
        bar,
        zu,
        replay,
        plum,
        watermelon,
      ];

  static List<SlotSymbol> get third => [
        bell,
        replay,
        watermelon,
        bell,
        plum,
        da,
        replay,
        watermelon,
        plum,
        cherry,
        bar,
        replay,
        watermelon,
        bell,
        plum,
        cherry,
        zu,
        replay,
        watermelon,
        nn,
        plum,
      ];

  int get point => switch (this) {
        bell => 30,
        bar => 50,
        cherry => 3,
        plum => 6,
        replay => 3,
        zu || nn || da => 10,
        watermelon => 15,
      };
}
